### ISSUE TITLE
cloudsmith package link

### ISSUE THREAD

**Issue by lakshya-aga** [CamFlow/camflow-install#10]
When $curl -1sLf 'https://dl.cloudsmith.io/public/camflow/camflow/cfg/setup/bash.rpm.sh' | sudo -E bash
is executed, we get an error, invalid bash command. On checking cloudsmith, cannot find the .sh file to link to this command.

**Comment by LouisLiuNova** [comment]
Yes, I could not connect Cloudsmith inside my VM. To be honest, I cannot install `camflow` at all.

**Comment by tfjmp** [comment]
I advise you to try this VM: https://github.com/CamFlow/vagrant/tree/master/rpm

I tested it this morning it worked properly.
