### ISSUE TITLE
How to decrypt MQTT data?

### ISSUE THREAD

**Issue by polosec** [CamFlow/camflow-install#11]
I use MQTT to transmit collected provenance data, but from the server, I saw the data was encrypted like AES, how to decrypt it to use and understand it?

**Comment by tfjmp** [comment]
It is not encrypted. It is just compressed (zlib): 
https://github.com/CamFlow/camflowd/blob/master/include/service-mqtt.h#L134

Here is an example of decompression in JS: https://github.com/CamFlow/cytoscape.js-prov/blob/master/cytoscape-prov-mqtt.js#L33

I hope that helps.

**Comment by polosec** [comment]
thanks！
