### ISSUE TITLE
About prov:type in camflow

### ISSUE THREAD

**Issue by morningphase** [CamFlow/camflow-install#8]
In my actual operation, I find that the value of prov:type might be "socket", "packet", etc. I want to know what values can be assigned in camflow prov:type and what the meaning of these values is

**Comment by tfjmp** [comment]
I believe the information you need is [here ](https://github.com/CamFlow/camflow-dev/blob/master/docs/RELATIONS.md) and [there](https://github.com/CamFlow/camflow-dev/blob/master/docs/VERTICES.md). I hope this helps.
